export const baseUrl = "https://m.you.163.com";

///首页
export const URL_HOME_NEW = baseUrl + '/xhr/index.json';

/// 首页推荐列表
export const URL_ITEM = baseUrl + '/xhr/index/items.json'

/// 分类
export const SORT_DATA = baseUrl + '/item/cateList.json'

/// 值得买头部数据
export const TOPIC_NAVWAP = baseUrl + '/topic/v1/know/navWap.json'

/// 值得买头部数据
export const TOPIC_LIST = baseUrl + '/topic/v1/find/recAuto.json'



