export const baseUrl = 'https://m.you.163.com';

export const LOGIN_PAGE_URL = "https://m.you.163.com/u/login";

///首页
export const URL_HOME_NEW = baseUrl + '/xhr/index.json';

/// 首页推荐列表
export const URL_ITEM = baseUrl + '/xhr/index/items.json'

/// 分类
export const SORT_DATA = baseUrl + '/item/cateList.json'

/// 值得买头部数据
export const TOPIC_NAVWAP = baseUrl + '/topic/v1/know/navWap.json'

/// 值得买头部数据
export const TOPIC_LIST = baseUrl + '/topic/v1/find/recAuto.json'

///热销榜/标题
export const HOT_LIST_CAT = baseUrl + '/item/saleRank.json';

///热销榜/条目
export const HOT_LIST_LIST = baseUrl + '/xhr/item/saleRankItems.json';

///热销榜名单
export const SUBMIT_ORDER_INFO = baseUrl + '/xhr/item/getSubmitOrderInfo.json';

/// kingkong
export const URL_KING_KONG = baseUrl + '/item/list.json';

/// kingkong
export const GOOD_DETAIL = baseUrl + '/item/detail.json';

/// 详情领券
export const DETAIL_AND_USER = baseUrl + '/xhr/item/queryByItemAndUser.json';

/// 配送信息
export const WAPITEM_DELIVERY = baseUrl + '/xhr/wapitem/delivery.json';

/// 商品详情推荐
export const WAPITEM_RCMD = baseUrl + '/xhr/wapitem/rcmd.json';

///商品详情品牌研究所
export const BRAND_INFO = baseUrl + '/xhr/brand/info.json';

///商品详情品牌研究所
export const BRAND_INFO_ITEMS = baseUrl + '/xhr/item/brand/index.json';

/// 分类列表
export const URL_SORT_LIST_NEW = baseUrl + '/item/list.json';

///好评率
export const COMMENT_PRAISE = baseUrl + '/xhr/comment/itemGoodRates.json';

///评价tags
export const COMMENT_TAGS = baseUrl + '/xhr/comment/tags.json';

///评论
export const COMMENT_LIST = baseUrl + '/xhr/comment/listByItemByTag.json';

///检查登录GET
export const CHECK_LOGIN = baseUrl + '/xhr/common/checklogin.json';

