export const textBlack = $r('app.color.text_black')

export const appRed = $r('app.color.primary_color')
export const appWhite = $r('app.color.app_white')
export const darkRed = $r('app.color.app_dark_red')
export const backRed = $r('app.color.back_red')
export const backRedLight = $r('app.color.back_red_light')
export const backBlack = $r('app.color.back_black')

export const textRed = $r('app.color.text_red')
export const textLightRed = $r('app.color.text_light_red')
export const textYellow = $r('app.color.text_yellow')
export const textWhite = Color.White
export const textGray = $r('app.color.text_gray')
export const lineColor = $r('app.color.text_light_gray')
export const textLightGray = $r('app.color.text_light_gray')
export const backgroundColor = $r('app.color.back_ground_color')
