export const textBlack = $r('app.color.text_black')

export const appRed = $r('app.color.primary_color')
export const darkRed = $r('app.color.app_dark_red')

export const textRed = $r('app.color.text_red')
export const textWhite = Color.White
export const textGray = $r('app.color.text_gray')
export const lineColor = $r('app.color.text_light_gray')
export const textLightGray = $r('app.color.text_light_gray')
export const backgroundColor = $r('app.color.back_ground_color')
