export class CouponModel {
  code: string
  validStartTime: number
  couponItemPath: string
  appOnly: boolean
  buttonFlag: boolean
  type: number
  baseActiveNewUserOnly: number
  path: string
  usable: boolean
  unit: string
  hasCoupon: boolean
  newUserOnly: number
  validEndTime: number
  briefDesc: string
  useCondition: string
  name: string
  timeDesc: string
  useTime: number
  activationCode: string
  id: number
  albeToActivated: boolean
  isSelected: boolean
}